version: '3.1'

services:
  aggregation-contract-app:
    build: ./
    ports:
      - "8080:8080"
    links:
      - external-api-app


  external-api-app:
    image: qwkz/backend-services:latest
    ports:
      - "4000:4000"


  elasticsearch:
    image: elasticsearch:8.0.1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data:z
    ports:
      - "9200:9200"
    environment:
      ES_JAVA_OPTS: -Xmx256m -Xms256m
      discovery.type: single-node
      xpack.security.enabled: false
      logger.level: ERROR

  kibana:
    image: kibana:8.0.1
    ports:
      - "5601:5601"

  filebeat:
    image: elastic/filebeat:8.0.1
    user: root
    volumes:
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - type: bind
        source: /var/lib/docker/containers
        target: /var/lib/docker/containers
        read_only: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true

volumes:
  elasticsearch:
